# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InvestInShares.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(480, -40, 20, 1141))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_name_share = QtWidgets.QLabel(self.centralwidget)
        self.label_name_share.setGeometry(QtCore.QRect(30, 90, 491, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_name_share.setFont(font)
        self.label_name_share.setObjectName("label_name_share")
        self.label_price = QtWidgets.QLabel(self.centralwidget)
        self.label_price.setGeometry(QtCore.QRect(190, 200, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_price.setFont(font)
        self.label_price.setObjectName("label_price")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 320, 271, 141))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_list_shares = QtWidgets.QLabel(self.centralwidget)
        self.label_list_shares.setGeometry(QtCore.QRect(550, 20, 861, 761))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_list_shares.setFont(font)
        self.label_list_shares.setObjectName("label_list_shares")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name_share.setText(_translate("MainWindow", "Акція"))
        self.label_price.setText(_translate("MainWindow", "Ціна"))
        self.pushButton.setText(_translate("MainWindow", "КУПИТИ"))
        self.label_list_shares.setText(_translate("MainWindow", "СПИСОК АКЦІЙ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
