# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PersonalAccount.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(1150, -30, 20, 1121))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_photo = QtWidgets.QLabel(self.centralwidget)
        self.label_photo.setGeometry(QtCore.QRect(1570, 0, 351, 341))
        self.label_photo.setAutoFillBackground(False)
        self.label_photo.setText("")
        self.label_photo.setPixmap(QtGui.QPixmap("img_for_project/Слісаренко/user_photo.png"))
        self.label_photo.setScaledContents(True)
        self.label_photo.setWordWrap(False)
        self.label_photo.setObjectName("label_photo")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(1480, 380, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_name.setFont(font)
        self.label_name.setTextFormat(QtCore.Qt.AutoText)
        self.label_name.setObjectName("label_name")
        self.label_balance = QtWidgets.QLabel(self.centralwidget)
        self.label_balance.setGeometry(QtCore.QRect(1180, 490, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_balance.setFont(font)
        self.label_balance.setObjectName("label_balance")
        self.pushButton_Deposit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Deposit.setGeometry(QtCore.QRect(1260, 600, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Deposit.setFont(font)
        self.pushButton_Deposit.setObjectName("pushButton_Deposit")
        self.pushButton_withdraw = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_withdraw.setGeometry(QtCore.QRect(1580, 600, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_withdraw.setFont(font)
        self.pushButton_withdraw.setObjectName("pushButton_withdraw")
        self.label_h = QtWidgets.QLabel(self.centralwidget)
        self.label_h.setGeometry(QtCore.QRect(0, 0, 391, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_h.setFont(font)
        self.label_h.setObjectName("label_h")
        self.label_history = QtWidgets.QLabel(self.centralwidget)
        self.label_history.setGeometry(QtCore.QRect(10, 100, 1141, 971))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_history.setFont(font)
        self.label_history.setObjectName("label_history")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name.setText(_translate("MainWindow", "Denys Slisarenko"))
        self.label_balance.setText(_translate("MainWindow", "Ваш баланс : "))
        self.pushButton_Deposit.setText(_translate("MainWindow", "Поповнити"))
        self.pushButton_withdraw.setText(_translate("MainWindow", "Вивести"))
        self.label_h.setText(_translate("MainWindow", "Історія покупок : "))
        self.label_history.setText(_translate("MainWindow", "(ІСТОРІЯ)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
