# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authorization.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registration_Form(object):
    def setupUi(self, Registration_Form):
        Registration_Form.setObjectName("Registration_Form")
        Registration_Form.resize(640, 484)
        self.label = QtWidgets.QLabel(Registration_Form)
        self.label.setGeometry(QtCore.QRect(240, 80, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(Registration_Form)
        self.layoutWidget.setGeometry(QtCore.QRect(160, 130, 301, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Login_line = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Login_line.setFont(font)
        self.Login_line.setObjectName("Login_line")
        self.verticalLayout.addWidget(self.Login_line)
        self.Password_line = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Password_line.setFont(font)
        self.Password_line.setObjectName("Password_line")
        self.verticalLayout.addWidget(self.Password_line)
        self.Enter_button = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Enter_button.setFont(font)
        self.Enter_button.setObjectName("Enter_button")
        self.verticalLayout.addWidget(self.Enter_button)
        self.Forgot_password_button = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Forgot_password_button.setFont(font)
        self.Forgot_password_button.setObjectName("Forgot_password_button")
        self.verticalLayout.addWidget(self.Forgot_password_button)
        self.label_2 = QtWidgets.QLabel(Registration_Form)
        self.label_2.setGeometry(QtCore.QRect(230, 390, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Registration_Form)
        self.pushButton.setGeometry(QtCore.QRect(230, 420, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Registration_Form)
        QtCore.QMetaObject.connectSlotsByName(Registration_Form)

    def retranslateUi(self, Registration_Form):
        _translate = QtCore.QCoreApplication.translate
        Registration_Form.setWindowTitle(_translate("Registration_Form", "Authorixation"))
        self.label.setText(_translate("Registration_Form", "Вхід у акаунт"))
        self.Login_line.setPlaceholderText(_translate("Registration_Form", "Login..."))
        self.Password_line.setPlaceholderText(_translate("Registration_Form", "Password..."))
        self.Enter_button.setText(_translate("Registration_Form", "Sign In"))
        self.Forgot_password_button.setText(_translate("Registration_Form", "Forgot password"))
        self.label_2.setText(_translate("Registration_Form", "Бажаєте зареструватись?"))
        self.pushButton.setText(_translate("Registration_Form", "Зареєструватись"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Registration_Form = QtWidgets.QWidget()
    ui = Ui_Registration_Form()
    ui.setupUi(Registration_Form)
    Registration_Form.show()
    sys.exit(app.exec_())
