# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Authorization_Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Authorization_Form(object):
    def setupUi(self, Authorization_Form):
        Authorization_Form.setObjectName("Authorization_Form")
        Authorization_Form.resize(335, 159)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Authorization_Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Login_line = QtWidgets.QLineEdit(Authorization_Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Login_line.setFont(font)
        self.Login_line.setObjectName("Login_line")
        self.verticalLayout.addWidget(self.Login_line)
        self.Password_line = QtWidgets.QLineEdit(Authorization_Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Password_line.setFont(font)
        self.Password_line.setObjectName("Password_line")
        self.verticalLayout.addWidget(self.Password_line)
        self.Enter_button = QtWidgets.QPushButton(Authorization_Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Enter_button.setFont(font)
        self.Enter_button.setObjectName("Enter_button")
        self.verticalLayout.addWidget(self.Enter_button)
        self.Forgot_password_button = QtWidgets.QPushButton(Authorization_Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Forgot_password_button.setFont(font)
        self.Forgot_password_button.setObjectName("Forgot_password_button")
        self.verticalLayout.addWidget(self.Forgot_password_button)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Authorization_Form)
        QtCore.QMetaObject.connectSlotsByName(Authorization_Form)

    def retranslateUi(self, Authorization_Form):
        _translate = QtCore.QCoreApplication.translate
        Authorization_Form.setWindowTitle(_translate("Authorization_Form", "Authorization_Form"))
        self.Login_line.setPlaceholderText(_translate("Authorization_Form", "Login..."))
        self.Password_line.setPlaceholderText(_translate("Authorization_Form", "Password..."))
        self.Enter_button.setText(_translate("Authorization_Form", "Enter"))
        self.Forgot_password_button.setText(_translate("Authorization_Form", "Forgot password"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Authorization_Form = QtWidgets.QWidget()
    ui = Ui_Authorization_Form()
    ui.setupUi(Authorization_Form)
    Authorization_Form.show()
    sys.exit(app.exec_())
